=== moueza/javaJ2EE/J2EEimie/workspaceJ2EE/XMLprof/exemples/produits/produits.dtd
<!ELEMENT produits (articles+)>
<!ELEMENT articles (nom,num,fabricant,prix+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT fabricant (entreprise,ville?)>
<!ELEMENT entreprise (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ATTLIST prix client (commerce|prive) #REQUIRED>

=== moueza/javaJ2EE/J2EEimie/workspaceJ2EE/XMLprof/exemples/produits/produits.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE produits SYSTEM "produits.dtd">
<produits>
	<articles>
		<nom>Poupée</nom>
		<num>32945-38</num>
		<fabricant>
			<entreprise>Jeubois</entreprise>
			<ville>Strasbourg</ville>
		</fabricant>
		<prix client="prive">60</prix>
		<prix client="commerce">40</prix>
	</articles>
	<articles>
		<nom>Polichinelle en bois</nom>
		<num>32945-41</num>
		<fabricant>
			<entreprise>Jeubois</entreprise>
			<ville>Strasbourg</ville>
		</fabricant>
		<prix client="prive">18</prix>
		<prix client="commerce">12</prix>
	</articles>
	<articles>
		<nom>Train en bois de base</nom>
		<num>32945-41</num>
		<fabricant>
			<entreprise>Natura SA</entreprise>
		</fabricant>
		<prix client="prive">80</prix>
		<prix client="commerce">60</prix>
	</articles>
</produits>
